### ISSUE TITLE
Certain bees don't respect special treat requirements

### ISSUE THREAD

**Issue by rythin-sr** [PiotrO15/Verdant-Idea#6] opened 2024-11-15 15:57 UTC
Verdant Idea 0.1.1

Occured to me when trying to get a leafcutter bee, putting a honey treat in a dirt nest. A chocolate mining bee spawned, which is supposed to require redstone essence as it's treat according to JEI.

**Comment by PiotrO15** [comment] 2024-11-15 19:54
This issue is caused by Productive Bees, since the item used to spawn bees is only known in the beginning of the countdown.

Will require changing bee spawning recipes so there are never 2 different items that can be used under the same conditions.

**Comment by PiotrO15** [comment] 2024-11-20 13:02
Fixed in 0.2.0

**Closed as completed by PiotrO15** 2024-11-20 13:02 UTC
Labels: Mod Bug
